export const typeActions = {
    ADD_LIST_CURRENCY: "ADD_LIST_CURRENCY",
    ADD_LIST_VACANCY: "ADD_LIST_VACANCY",
    ADD_LIST_AREA: "ADD_LIST_AREA",
    VACANCY_SORT: "VACANCY_SORT",
    VACANCY_FILTER_COUNTRY: "VACANCY_FILTER_COUNTRY"
};